


---- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP_PRE]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP_PRE]
CREATE TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP_PRE] (
	-- Period
	[YEAR (Yyyyy)]							VARCHAR(MAX) NULL,
	[YEAR (Yyy)]							VARCHAR(MAX) NULL,
	[QUARTER (yyyyQq)]						VARCHAR(MAX) NULL,
	[QUARTER (yyQq)]						VARCHAR(MAX) NULL,
	[MONTH (yyyyMmm)]						VARCHAR(MAX) NULL,
	[MONTH (yyMmm)]							VARCHAR(MAX) NULL,

	-- Organization
	[GROUP_CODE_ORIGINAL]					VARCHAR(MAX) NULL,
	[SUBGROUP_CODE_ORIGINAL]				VARCHAR(MAX) NULL,
	[DIV_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_CURRENT]						VARCHAR(MAX) NULL,

	-- Product
	[PRODUCT]								VARCHAR(MAX) NULL,
	[CP]									VARCHAR(MAX) NULL,
	[PRODUCT_LINE_ORIGINAL]					VARCHAR(MAX) NULL,
	[PRODUCT_LINE_CURRENT]					VARCHAR(MAX) NULL,

	-- Reason
	[REASON_CODE]							VARCHAR(MAX) NULL,
	[REASON_DESCR]							VARCHAR(MAX) NULL,
	[REASON_TYPE]							VARCHAR(MAX) NULL,
	[REASON_FLAG_QUANTITY]					VARCHAR(MAX) NULL,

	-- PNL Structure
	[ACTIVITY]								VARCHAR(MAX) NULL,
	[PLINE]									VARCHAR(MAX) NULL,
	[PLINE_DESCR]							VARCHAR(MAX) NULL,
	[LEVEL0]								VARCHAR(MAX) NULL,
	[LEVEL1]								VARCHAR(MAX) NULL,
	[LEVEL1_DESCR]							VARCHAR(MAX) NULL,
	[LEVEL2]								VARCHAR(MAX) NULL,
	[LEVEL2_DESCR]							VARCHAR(MAX) NULL,
	[LEVEL3]								VARCHAR(MAX) NULL,
	[LEVEL3_DESCR]							VARCHAR(MAX) NULL,

	-- Customer Direct
	[CUSTOMER_DIRECT_CODE]					VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_DESCR]					VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_TYPE_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_TYPE_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_GROUP_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_GROUP_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SHIPTO_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SHIPTO_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_REGION_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_REGION_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SALES_AREA_CODE]		VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SALES_AREA_DESCR]		VARCHAR(MAX) NULL,

	-- Customer Final
	[CUSTOMER_FINAL_CODE]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_DESCR]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_DESCR]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_REGION_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_REGION_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SALES_AREA_CODE]		VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SALES_AREA_DESCR]		VARCHAR(MAX) NULL,

	-- Other
	[RECORD_TYPE]							VARCHAR(MAX) NULL,
	[COMPANY_CODE]							VARCHAR(MAX) NULL,
	[LOCATION]								VARCHAR(MAX) NULL,
	[SITE]									VARCHAR(MAX) NULL,
	[SENDER_COST_CENTER]					VARCHAR(MAX) NULL,

	-- Flag
	[POSTING_IN_TARIFF301]					VARCHAR(MAX) NULL,

	-- Data
	[GROSS_SALES_QTY]						FLOAT NULL,
	[NET_QTY]								FLOAT NULL,
	[NET_QTY_BIBA]							FLOAT NULL,

	[SALES_PRODUCT] 						FLOAT NULL,
	[SALES_MATERIALS] 						FLOAT NULL,
	[GROSS_SALES]							FLOAT NULL,
	[RETURNS]								FLOAT NULL,
	[OTHER_DEDUCTIONS]						FLOAT NULL,
	[NET_SALES]								FLOAT NULL,
	[OTHER_REVENUES]						FLOAT NULL,
	[NET_REVENUES]							FLOAT NULL

) ON [PRIMARY]







---- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP]
CREATE TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP] (

	-- Period
	[YEAR (Yyyyy)]							VARCHAR(MAX) NULL,
	[YEAR (Yyy)]							VARCHAR(MAX) NULL,
	[QUARTER (yyyyQq)]						VARCHAR(MAX) NULL,
	[QUARTER (yyQq)]						VARCHAR(MAX) NULL,
	[MONTH (yyyyMmm)]						VARCHAR(MAX) NULL,
	[MONTH (yyMmm)]							VARCHAR(MAX) NULL,

	-- Organization
	[GROUP_CODE_ORIGINAL]					VARCHAR(MAX) NULL,
	[SUBGROUP_CODE_ORIGINAL]				VARCHAR(MAX) NULL,
	[DIV_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_CURRENT]						VARCHAR(MAX) NULL,

	-- Product
	[CP]									VARCHAR(MAX) NULL,
	[PRODUCT_LINE_ORIGINAL]					VARCHAR(MAX) NULL,
	[PRODUCT_LINE_CURRENT]					VARCHAR(MAX) NULL,

	-- Reason
	[REASON_CODE]							VARCHAR(MAX) NULL,
	[REASON_DESCR]							VARCHAR(MAX) NULL,
	[REASON_TYPE]							VARCHAR(MAX) NULL,
	[REASON_FLAG_QUANTITY]					VARCHAR(MAX) NULL,

	-- Customer Direct
	[CUSTOMER_DIRECT_CODE]					VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_DESCR]					VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_TYPE_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_TYPE_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_GROUP_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_GROUP_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SHIPTO_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SHIPTO_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_REGION_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_REGION_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SALES_AREA_CODE]		VARCHAR(MAX) NULL,
	[CUSTOMER_DIRECT_SALES_AREA_DESCR]		VARCHAR(MAX) NULL,

	-- Customer Final
	[CUSTOMER_FINAL_CODE]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_DESCR]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_DESCR]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_REGION_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_REGION_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SALES_AREA_CODE]		VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SALES_AREA_DESCR]		VARCHAR(MAX) NULL,

	-- Data
	[NET_QTY]								FLOAT NULL,
	[NET_QTY_BIBA]							FLOAT NULL,
	[NET_REVENUES]							FLOAT NULL

) ON [PRIMARY]




---- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_SAP_ACT_MONTH]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_MONTH]
CREATE TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_MONTH] (
	[MONTH]		VARCHAR(MAX) NULL

) ON [PRIMARY]


