

-- Drop tables
-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP_PRE]') 		IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP_PRE]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP]') 			IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_TEMP]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_SAP_ACT_MONTH]') 		IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACT_MONTH]




