


-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_TEMP]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_TEMP]

CREATE TABLE [ROYALTY].[dbo].[ROYALTY_TEMP](
	[ROYALTY_ID]							VARCHAR(MAX) NULL,

	-- Period
	[YEAR (Yyyyy)]							VARCHAR(MAX) NULL,
	[YEAR (Yyy)]							VARCHAR(MAX) NULL,
	[QUARTER (yyyyQq)]						VARCHAR(MAX) NULL,
	[QUARTER (yyQq)]						VARCHAR(MAX) NULL,
	[MONTH (yyyyMmm)]						VARCHAR(MAX) NULL,
	[MONTH (yyMmm)]							VARCHAR(MAX) NULL,

	-- Organization
	[GROUP_CODE_ORIGINAL]					VARCHAR(MAX) NULL,
	[SUB_GROUP_CODE_ORIGINAL]				VARCHAR(MAX) NULL,
	[DIV_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_CURRENT]						VARCHAR(MAX) NULL,

	-- Source
	[DATA_SOURCE]							VARCHAR(MAX) NULL,

	-- Product
	[PRODUCT_LINE_ORIGINAL]					VARCHAR(MAX) NULL,
	[PRODUCT_LINE_CURRENT] 					VARCHAR(MAX) NULL,
	[CP]									VARCHAR(MAX) NULL,

	-- Reason
	[REASON_CODE]							VARCHAR(MAX) NULL,
	[REASON_DESCR]							VARCHAR(MAX) NULL,
	[REASON_TYPE]							VARCHAR(MAX) NULL,
	[REASON_FLAG_QUANTITY]					VARCHAR(MAX) NULL,

	-- Customer Final
	[CUSTOMER_FINAL_CODE]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_DESCR]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_DESCR]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_DESCR]			VARCHAR(MAX) NULL,

	-- Royalty
	[AGREEMENT]								VARCHAR(MAX) NULL,
	[CONDITION]								VARCHAR(MAX) NULL,
	[LCL_CURRENCY]							VARCHAR(MAX) NULL,
	[EXCHANGE_RATE]							FLOAT NULL,

	[NET_REVENUE_LCL]						FLOAT NULL,
	[CUM_NET_REVENUE_LCL]					FLOAT NULL,

	[NET_REVENUE_USD]						FLOAT NULL,
	[CUM_NET_REVENUE_USD]					FLOAT NULL,

	[NET_QTY_PCS]							FLOAT NULL,
	[CUM_NET_QTY_PCS]						FLOAT NULL,

	[ROYALTY_LCL]							FLOAT NULL,
	[CUM_ROYALTY_LCL]						FLOAT NULL,

	[ROYALTY_USD]							FLOAT NULL,
	[CUM_ROYALTY_USD]						FLOAT NULL,

	[ROYALTY_PAID_LCL]						FLOAT NULL,
	[CUM_ROYALTY_PAID_LCL]					FLOAT NULL,

	[ROYALTY_PAID_USD]						FLOAT NULL,
	[CUM_ROYALTY_PAID_USD]					FLOAT NULL
	
) ON [PRIMARY]




