

-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY]

CREATE TABLE [ROYALTY].[dbo].[ROYALTY](
	[ROYALTY_ID]							VARCHAR(MAX) NULL,

	-- Period
	[YEAR (Yyyyy)]							VARCHAR(MAX) NULL,
	[YEAR (Yyy)]							VARCHAR(MAX) NULL,
	[QUARTER (yyyyQq)]						VARCHAR(MAX) NULL,
	[QUARTER (yyQq)]						VARCHAR(MAX) NULL,
	[MONTH (yyyyMmm)]						VARCHAR(MAX) NULL,
	[MONTH (yyMmm)]							VARCHAR(MAX) NULL,

	-- Organization
	[GROUP_CODE_ORIGINAL]					VARCHAR(MAX) NULL,
	[SUB_GROUP_CODE_ORIGINAL]				VARCHAR(MAX) NULL,
	[DIV_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_ORIGINAL]						VARCHAR(MAX) NULL,
	[BU_CODE_CURRENT]						VARCHAR(MAX) NULL,

	-- Source
	[DATA_SOURCE]							VARCHAR(MAX) NULL,

	-- Product
	[PRODUCT_LINE_ORIGINAL]					VARCHAR(MAX) NULL,
	[PRODUCT_LINE_CURRENT] 					VARCHAR(MAX) NULL,
	[CP]									VARCHAR(MAX) NULL,

	-- Reason
	[REASON_CODE]							VARCHAR(MAX) NULL,
	[REASON_DESCR]							VARCHAR(MAX) NULL,
	[REASON_TYPE]							VARCHAR(MAX) NULL,
	[REASON_FLAG_QUANTITY]					VARCHAR(MAX) NULL,

	-- Customer Final
	[CUSTOMER_FINAL_CODE]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_DESCR]					VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_TYPE_DESCR]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_CODE]				VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_GROUP_DESCR]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_CODE]			VARCHAR(MAX) NULL,
	[CUSTOMER_FINAL_SHIPTO_DESCR]			VARCHAR(MAX) NULL,

	-- Royalty
	[AGREEMENT]								VARCHAR(MAX) NULL,
	[CONDITION]								VARCHAR(MAX) NULL,
	[LCL_CURRENCY]							VARCHAR(MAX) NULL,
	[EXCHANGE_RATE]							FLOAT NULL,

	[NET_REVENUE_LCL]						FLOAT NULL,
	[CUM_NET_REVENUE_LCL]					FLOAT NULL,

	[NET_REVENUE_USD]						FLOAT NULL,
	[CUM_NET_REVENUE_USD]					FLOAT NULL,

	[NET_QTY_PCS]							FLOAT NULL,
	[CUM_NET_QTY_PCS]						FLOAT NULL,

	[ROYALTY_LCL]							FLOAT NULL,
	[CUM_ROYALTY_LCL]						FLOAT NULL,

	[ROYALTY_USD]							FLOAT NULL,
	[CUM_ROYALTY_USD]						FLOAT NULL,

	[ROYALTY_PAID_LCL]						FLOAT NULL,
	[CUM_ROYALTY_PAID_LCL]					FLOAT NULL,

	[ROYALTY_PAID_USD]						FLOAT NULL,
	[CUM_ROYALTY_PAID_USD]					FLOAT NULL
	
) ON [PRIMARY]





-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_AGREEMENT]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_AGREEMENT]

CREATE TABLE [ROYALTY].[dbo].[ROYALTY_AGREEMENT](
	[AGREEMENT_ID]									VARCHAR(MAX) NULL,

	-- Agreement
	[AGREEMENT]										VARCHAR(MAX) NULL,

	-- Versioning
	[VERSION_DATE]									VARCHAR(MAX) NULL,
	[VERSION_DESCR]									VARCHAR(MAX) NULL,

	-- Model
	[MODEL_ACTIVE]									VARCHAR(MAX) NULL,
	[MODEL_INITIAL_MONTH]							VARCHAR(MAX) NULL,
	[MODEL_FINAL_MONTH]								VARCHAR(MAX) NULL,
	[MODEL_TYPE]									VARCHAR(MAX) NULL,
	[MODEL_CURRENCY]								VARCHAR(MAX) NULL,
	[MODEL_NB_SLOT]									FLOAT NULL,
	[MODEL_MIN_ACCUMULATED_ROYALTY]					FLOAT NULL,
	[MODEL_MIN_EACH_YEAR_ROYALTY]					FLOAT NULL,
	[MODEL_MIN_EACH_QUARTER_ROYALTY]				FLOAT NULL,
	[MODEL_MAX_ACCUMULATED_ROYALTY]					FLOAT NULL,
	[MODEL_MAX_EACH_YEAR_ROYALTY]					FLOAT NULL,
	[MODEL_MAX_EACH_QUARTER_ROYALTY]				FLOAT NULL,

	-- Products selection
	[SELECTION_PL_LIST]								VARCHAR(MAX) NULL,
	[SELECTION_CP_LIST]								VARCHAR(MAX) NULL,
	[SELECTION_CP_CONDITION]						VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_LIST]					VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_CONDITION]			VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_TYPE_LIST]			VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_TYPE_CONDITION]		VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_GROUP_LIST]			VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_GROUP_CONDITION]		VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_SHIPTO_LIST]			VARCHAR(MAX) NULL,
	[SELECTION_CUSTOMER_FINAL_SHIPTO_CONDITION]		VARCHAR(MAX) NULL,

	--Slot 01
	[SLOT01_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT01_START]									FLOAT NULL,
	[SLOT01_END]									FLOAT NULL,
	[SLOT01_RATE]									FLOAT NULL,
	[SLOT01_MIN]									FLOAT NULL,
	[SLOT01_MAX]									FLOAT NULL,
	[SLOT01_A]										VARCHAR(MAX) NULL,
	[SLOT01_B]										VARCHAR(MAX) NULL,
	[SLOT01_C]										VARCHAR(MAX) NULL,
	[SLOT01_D]										VARCHAR(MAX) NULL,
	[SLOT01_E]										VARCHAR(MAX) NULL,
	[SLOT01_F]										VARCHAR(MAX) NULL,
	[SLOT01_G]										VARCHAR(MAX) NULL,
	[SLOT01_H]										VARCHAR(MAX) NULL,

	--Slot 02
	[SLOT02_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT02_START]									FLOAT NULL,
	[SLOT02_END]									FLOAT NULL,
	[SLOT02_RATE]									FLOAT NULL,
	[SLOT02_MIN]									FLOAT NULL,
	[SLOT02_MAX]									FLOAT NULL,
	[SLOT02_A]										VARCHAR(MAX) NULL,
	[SLOT02_B]										VARCHAR(MAX) NULL,
	[SLOT02_C]										VARCHAR(MAX) NULL,
	[SLOT02_D]										VARCHAR(MAX) NULL,
	[SLOT02_E]										VARCHAR(MAX) NULL,
	[SLOT02_F]										VARCHAR(MAX) NULL,
	[SLOT02_G]										VARCHAR(MAX) NULL,
	[SLOT02_H]										VARCHAR(MAX) NULL,

	--Slot 03
	[SLOT03_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT03_START]									FLOAT NULL,
	[SLOT03_END]									FLOAT NULL,
	[SLOT03_RATE]									FLOAT NULL,
	[SLOT03_MIN]									FLOAT NULL,
	[SLOT03_MAX]									FLOAT NULL,
	[SLOT03_A]										VARCHAR(MAX) NULL,
	[SLOT03_B]										VARCHAR(MAX) NULL,
	[SLOT03_C]										VARCHAR(MAX) NULL,
	[SLOT03_D]										VARCHAR(MAX) NULL,
	[SLOT03_E]										VARCHAR(MAX) NULL,
	[SLOT03_F]										VARCHAR(MAX) NULL,
	[SLOT03_G]										VARCHAR(MAX) NULL,
	[SLOT03_H]										VARCHAR(MAX) NULL,

	--Slot 04
	[SLOT04_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT04_START]									FLOAT NULL,
	[SLOT04_END]									FLOAT NULL,
	[SLOT04_RATE]									FLOAT NULL,
	[SLOT04_MIN]									FLOAT NULL,
	[SLOT04_MAX]									FLOAT NULL,
	[SLOT04_A]										VARCHAR(MAX) NULL,
	[SLOT04_B]										VARCHAR(MAX) NULL,
	[SLOT04_C]										VARCHAR(MAX) NULL,
	[SLOT04_D]										VARCHAR(MAX) NULL,
	[SLOT04_E]										VARCHAR(MAX) NULL,
	[SLOT04_F]										VARCHAR(MAX) NULL,
	[SLOT04_G]										VARCHAR(MAX) NULL,
	[SLOT04_H]										VARCHAR(MAX) NULL,

	--Slot 05
	[SLOT05_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT05_START]									FLOAT NULL,
	[SLOT05_END]									FLOAT NULL,
	[SLOT05_RATE]									FLOAT NULL,
	[SLOT05_MIN]									FLOAT NULL,
	[SLOT05_MAX]									FLOAT NULL,
	[SLOT05_A]										VARCHAR(MAX) NULL,
	[SLOT05_B]										VARCHAR(MAX) NULL,
	[SLOT05_C]										VARCHAR(MAX) NULL,
	[SLOT05_D]										VARCHAR(MAX) NULL,
	[SLOT05_E]										VARCHAR(MAX) NULL,
	[SLOT05_F]										VARCHAR(MAX) NULL,
	[SLOT05_G]										VARCHAR(MAX) NULL,
	[SLOT05_H]										VARCHAR(MAX) NULL,

	--Slot 06
	[SLOT06_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT06_START]									FLOAT NULL,
	[SLOT06_END]									FLOAT NULL,
	[SLOT06_RATE]									FLOAT NULL,
	[SLOT06_MIN]									FLOAT NULL,
	[SLOT06_MAX]									FLOAT NULL,
	[SLOT06_A]										VARCHAR(MAX) NULL,
	[SLOT06_B]										VARCHAR(MAX) NULL,
	[SLOT06_C]										VARCHAR(MAX) NULL,
	[SLOT06_D]										VARCHAR(MAX) NULL,
	[SLOT06_E]										VARCHAR(MAX) NULL,
	[SLOT06_F]										VARCHAR(MAX) NULL,
	[SLOT06_G]										VARCHAR(MAX) NULL,
	[SLOT06_H]										VARCHAR(MAX) NULL,

	--Slot 07
	[SLOT07_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT07_START]									FLOAT NULL,
	[SLOT07_END]									FLOAT NULL,
	[SLOT07_RATE]									FLOAT NULL,
	[SLOT07_MIN]									FLOAT NULL,
	[SLOT07_MAX]									FLOAT NULL,
	[SLOT07_A]										VARCHAR(MAX) NULL,
	[SLOT07_B]										VARCHAR(MAX) NULL,
	[SLOT07_C]										VARCHAR(MAX) NULL,
	[SLOT07_D]										VARCHAR(MAX) NULL,
	[SLOT07_E]										VARCHAR(MAX) NULL,
	[SLOT07_F]										VARCHAR(MAX) NULL,
	[SLOT07_G]										VARCHAR(MAX) NULL,
	[SLOT07_H]										VARCHAR(MAX) NULL,

	--Slot 08
	[SLOT08_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT08_START]									FLOAT NULL,
	[SLOT08_END]									FLOAT NULL,
	[SLOT08_RATE]									FLOAT NULL,
	[SLOT08_MIN]									FLOAT NULL,
	[SLOT08_MAX]									FLOAT NULL,
	[SLOT08_A]										VARCHAR(MAX) NULL,
	[SLOT08_B]										VARCHAR(MAX) NULL,
	[SLOT08_C]										VARCHAR(MAX) NULL,
	[SLOT08_D]										VARCHAR(MAX) NULL,
	[SLOT08_E]										VARCHAR(MAX) NULL,
	[SLOT08_F]										VARCHAR(MAX) NULL,
	[SLOT08_G]										VARCHAR(MAX) NULL,
	[SLOT08_H]										VARCHAR(MAX) NULL,

	--Slot 09
	[SLOT09_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT09_START]									FLOAT NULL,
	[SLOT09_END]									FLOAT NULL,
	[SLOT09_RATE]									FLOAT NULL,
	[SLOT09_MIN]									FLOAT NULL,
	[SLOT09_MAX]									FLOAT NULL,
	[SLOT09_A]										VARCHAR(MAX) NULL,
	[SLOT09_B]										VARCHAR(MAX) NULL,
	[SLOT09_C]										VARCHAR(MAX) NULL,
	[SLOT09_D]										VARCHAR(MAX) NULL,
	[SLOT09_E]										VARCHAR(MAX) NULL,
	[SLOT09_F]										VARCHAR(MAX) NULL,
	[SLOT09_G]										VARCHAR(MAX) NULL,
	[SLOT09_H]										VARCHAR(MAX) NULL,

	--Slot 10
	[SLOT10_MESSAGE]								VARCHAR(MAX) NULL,
	[SLOT10_START]									FLOAT NULL,
	[SLOT10_END]									FLOAT NULL,
	[SLOT10_RATE]									FLOAT NULL,
	[SLOT10_MIN]									FLOAT NULL,
	[SLOT10_MAX]									FLOAT NULL,
	[SLOT10_A]										VARCHAR(MAX) NULL,
	[SLOT10_B]										VARCHAR(MAX) NULL,
	[SLOT10_C]										VARCHAR(MAX) NULL,
	[SLOT10_D]										VARCHAR(MAX) NULL,
	[SLOT10_E]										VARCHAR(MAX) NULL,
	[SLOT10_F]										VARCHAR(MAX) NULL,
	[SLOT10_G]										VARCHAR(MAX) NULL,
	[SLOT10_H]										VARCHAR(MAX) NULL

) ON [PRIMARY]





-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_INIT]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_INIT]

CREATE TABLE [ROYALTY].[dbo].[ROYALTY_INIT](
	[AGREEMENT]						VARCHAR(MAX) NULL,
	[INITIAL_MONTH_OF_CONTRACT]		VARCHAR(MAX) NULL,
	[FINAL_MONTH_OF_CONTRACT]		VARCHAR(MAX) NULL,
	[MONTH_OF_INITIALIZATION]		VARCHAR(MAX) NULL,
	[CUM_NET_QTY_PCS]				FLOAT NULL,
	[CUM_NET_REVENUE_LCL]			FLOAT NULL,
	[CUM_NET_REVENUE_USD]			FLOAT NULL,
	[CUM_ROYALTY_LCL]				FLOAT NULL,
	[CUM_ROYALTY_USD]				FLOAT NULL,
	[CUM_ROYALTY_PAID_LCL]			FLOAT NULL,
	[CUM_ROYALTY_PAID_USD]			FLOAT NULL
) ON [PRIMARY]






-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_LIST_AGREEMENT]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_LIST_AGREEMENT]
CREATE TABLE [ROYALTY].[dbo].[ROYALTY_LIST_AGREEMENT] (
	[AGREEMENT]		VARCHAR(MAX) NULL,
) ON [PRIMARY]






-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_LIST_QUARTER_ACTUAL]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_LIST_QUARTER_ACTUAL]

CREATE TABLE [ROYALTY].[dbo].[ROYALTY_LIST_QUARTER_ACTUAL](
	[QUARTER (yyyyQq)]	VARCHAR(MAX) NULL
) ON [PRIMARY]






-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_LIST_PLAN]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_LIST_PLAN]
CREATE TABLE [ROYALTY].[dbo].[ROYALTY_LIST_PLAN] (
	[PLAN]		VARCHAR(MAX) NULL
) ON [PRIMARY]






-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_EXCHANGE_RATE]') IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_EXCHANGE_RATE]

CREATE TABLE [ROYALTY].[dbo].[ROYALTY_EXCHANGE_RATE](
	[QUARTER (yyyyQq)]	VARCHAR(MAX) NULL,
	[CURRENCY]			VARCHAR(MAX) NULL,
	[EXCHANGE_RATE]		FLOAT NULL	
) ON [PRIMARY]







