

-- Drop tables
-- ---------------------------------------------------
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_PERIOD]') 			IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_PERIOD]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_FORECAST]') 			IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_FORECAST]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_EXCHANGE_RATE]') 	IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_EXCHANGE_RATE]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_INIT]') 				IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_INIT]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_AGREEMENT]') 		IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_AGREEMENT]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_Q]') 				IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_Q]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_SAPACT_EPM_Q]') 		IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_SAPACT_EPM_Q]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_EPM_Q]') 			IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_EPM_Q]
IF OBJECT_ID('[ROYALTY].[dbo].[ROYALTY_CUM]') 				IS NOT NULL DROP TABLE [ROYALTY].[dbo].[ROYALTY_CUM]








