
-- Parameter
--------------------------------------------
DECLARE @Period_Active NVARCHAR(MAX)
DECLARE @Qtr2 NVARCHAR(MAX)
SET @Period_Active = ?
SET @Qtr2 = ?
--SET @Period_Active = 'Y'
--SET @Qtr2 = 'Q202501'


-- ---------------------------------------------------
TRUNCATE TABLE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q]

IF (@Period_Active = 'Y')
BEGIN

	-- Fino al 2022 compreso le Net Qty sono estratte da SAP. Dal 2023 compreso in poi invece da BIBA
	INSERT INTO [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q]

	SELECT
		'Y' + [YEAR] AS [YEAR (Yyyyy)],
		SUBSTRING([QTR],2,4) + 'Q' + SUBSTRING([QTR],7,1) AS [QUARTER (yyyyQq)],
		SUBSTRING([MONTH],2,4) + 'Q' + SUBSTRING([MONTH],6,2) AS [MONTH (yyyyMmm)],

		-- Organization
		[GROUP_CODE_ORIGINAL],
		[SUBGROUP_CODE_ORIGINAL] AS [SUB_GROUP_CODE_ORIGINAL],
		[DIV_CODE_ORIGINAL],
		[BU_CODE_ORIGINAL],
		[BU_CODE_CURRENT] AS [BU_CODE],

		-- Organization
		'ACTUAL' AS [DATA_SOURCE],

		-- Product
		[PRODUCT_LINE_CURRENT] AS [PRODUCT_LINE],
		[CP],

		-- Reason
		[REASON_CODE],
		[REASON_DESCR],
		[REASON_TYPE],
		[REASON_FLAG_QUANTITY],

		-- Customer Final
		[CUSTOMER_FINAL_CODE],
		REPLACE([CUSTOMER_FINAL_DESCR],'''','')	AS [CUSTOMER_FINAL_DESCR],
		[CUSTOMER_FINAL_TYPE_CODE],
		REPLACE([CUSTOMER_FINAL_TYPE_DESCR],'''','') AS [CUSTOMER_FINAL_TYPE_DESCR],
		[CUSTOMER_FINAL_GROUP_CODE],
		REPLACE([CUSTOMER_FINAL_GROUP_DESCR],'''','') AS [CUSTOMER_FINAL_GROUP_DESCR],
		[CUSTOMER_FINAL_SHIPTO_CODE],
		REPLACE([CUSTOMER_FINAL_SHIPTO_DESCR],'''','') AS [CUSTOMER_FINAL_SHIPTO_DESCR],

		-- Revenue, quantity
		SUM([NET_REVENUE_USD]) AS [NET_REVENUE_USD],
		IIF([QTR] <= 'Q202204', SUM([NET_QTY]), SUM([NET_QTY_BIBA])) AS [NET_QTY_PCS]

	FROM [AGRSW030.AGRMFG.STMMFG.COM].[ADG_CTLDM].[dbo].[SAP_ACTUALS_EXT]
	WHERE
		[QTR] = @Qtr2 AND
		[POSTING_IN_TARIFF301] = 'no_tariff_301'
	GROUP BY
		'Y' + [YEAR],
		SUBSTRING([QTR],2,4) + 'Q' + SUBSTRING([QTR],7,1),
		SUBSTRING([MONTH],2,4) + 'Q' + SUBSTRING([MONTH],6,2),
		[GROUP_CODE_ORIGINAL],
		[SUBGROUP_CODE_ORIGINAL],
		[DIV_CODE_ORIGINAL],
		[BU_CODE_ORIGINAL],
		[BU_CODE_CURRENT],
		[PRODUCT_LINE_CURRENT],
		[CP],
		[REASON_CODE],
		[REASON_DESCR],
		[REASON_TYPE],
		[REASON_FLAG_QUANTITY],
		[CUSTOMER_FINAL_CODE],
		REPLACE([CUSTOMER_FINAL_DESCR],'''',''),
		[CUSTOMER_FINAL_TYPE_CODE],
		REPLACE([CUSTOMER_FINAL_TYPE_DESCR],'''',''),
		[CUSTOMER_FINAL_GROUP_CODE],
		REPLACE([CUSTOMER_FINAL_GROUP_DESCR],'''',''),
		[CUSTOMER_FINAL_SHIPTO_CODE],
		REPLACE([CUSTOMER_FINAL_SHIPTO_DESCR],'''','')
	ORDER BY
		'Y' + [YEAR],
		SUBSTRING([QTR],2,4) + 'Q' + SUBSTRING([QTR],7,1),
		SUBSTRING([MONTH],2,4) + 'Q' + SUBSTRING([MONTH],6,2),
		[GROUP_CODE_ORIGINAL],
		[SUBGROUP_CODE_ORIGINAL],
		[DIV_CODE_ORIGINAL],
		[BU_CODE_ORIGINAL],
		[BU_CODE_CURRENT],
		[PRODUCT_LINE_CURRENT],
		[CP],
		[REASON_CODE],
		[REASON_DESCR],
		[REASON_TYPE],
		[REASON_FLAG_QUANTITY],
		[CUSTOMER_FINAL_CODE],
		REPLACE([CUSTOMER_FINAL_DESCR],'''',''),
		[CUSTOMER_FINAL_TYPE_CODE],
		REPLACE([CUSTOMER_FINAL_TYPE_DESCR],'''',''),
		[CUSTOMER_FINAL_GROUP_CODE],
		REPLACE([CUSTOMER_FINAL_GROUP_DESCR],'''',''),
		[CUSTOMER_FINAL_SHIPTO_CODE],
		REPLACE([CUSTOMER_FINAL_SHIPTO_DESCR],'''','')

END




-- Limita il numero di decimali di Qty e Rev. Puo' dare degli errori in alcuni casi
--------------------------------------------
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q]
SET 
	[NET_QTY_PCS] = ROUND([NET_QTY_PCS],3,0),
	[NET_REVENUE_USD] = ROUND([NET_REVENUE_USD],4,0)




-- Elimina row dove Rev=0 e Qty=0
--------------------------------------------
DELETE FROM [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q]
WHERE
	[NET_REVENUE_USD] = 0 AND
	[NET_QTY_PCS] = 0





-- Elimina NULL
--------------------------------------------
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [YEAR (Yyyyy)]					= 'X' WHERE [YEAR (Yyyyy)] IS NULL OR LEN([YEAR (Yyyyy)]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [QUARTER (yyyyQq)]				= 'X' WHERE [QUARTER (yyyyQq)] IS NULL OR LEN([QUARTER (yyyyQq)]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [MONTH (yyyyMmm)]				= 'X' WHERE [MONTH (yyyyMmm)] IS NULL OR LEN([MONTH (yyyyMmm)]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [GROUP_CODE_ORIGINAL]			= 'X' WHERE [GROUP_CODE_ORIGINAL] IS NULL OR LEN([GROUP_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [SUB_GROUP_CODE_ORIGINAL]		= 'X' WHERE [SUB_GROUP_CODE_ORIGINAL] IS NULL OR LEN([SUB_GROUP_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [DIV_CODE_ORIGINAL]				= 'X' WHERE [DIV_CODE_ORIGINAL] IS NULL OR LEN([DIV_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [BU_CODE_ORIGINAL]				= 'X' WHERE [BU_CODE_ORIGINAL] IS NULL OR LEN([BU_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [BU_CODE]						= 'X' WHERE [BU_CODE] IS NULL OR LEN([BU_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [DATA_SOURCE]					= 'X' WHERE [DATA_SOURCE] IS NULL OR LEN([DATA_SOURCE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [PRODUCT_LINE]					= 'X' WHERE [PRODUCT_LINE] IS NULL OR LEN([PRODUCT_LINE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CP]								= 'X' WHERE [CP] IS NULL OR LEN([CP]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [REASON_CODE]					= 'X' WHERE [REASON_CODE] IS NULL OR LEN([REASON_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [REASON_DESCR]					= 'X' WHERE [REASON_DESCR] IS NULL OR LEN([REASON_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [REASON_TYPE]					= 'X' WHERE [REASON_TYPE] IS NULL OR LEN([REASON_TYPE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [REASON_FLAG_QUANTITY]			= 'X' WHERE [REASON_FLAG_QUANTITY] IS NULL OR LEN([REASON_FLAG_QUANTITY]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_CODE]			= 'X' WHERE [CUSTOMER_FINAL_CODE] IS NULL OR LEN([CUSTOMER_FINAL_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_DESCR]			= 'X' WHERE [CUSTOMER_FINAL_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_TYPE_CODE]		= 'X' WHERE [CUSTOMER_FINAL_TYPE_CODE] IS NULL OR LEN([CUSTOMER_FINAL_TYPE_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_TYPE_DESCR]		= 'X' WHERE [CUSTOMER_FINAL_TYPE_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_TYPE_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_GROUP_CODE]		= 'X' WHERE [CUSTOMER_FINAL_GROUP_CODE] IS NULL OR LEN([CUSTOMER_FINAL_GROUP_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_GROUP_DESCR]		= 'X' WHERE [CUSTOMER_FINAL_GROUP_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_GROUP_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_SHIPTO_CODE]		= 'X' WHERE [CUSTOMER_FINAL_SHIPTO_CODE] IS NULL OR LEN([CUSTOMER_FINAL_SHIPTO_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [CUSTOMER_FINAL_SHIPTO_DESCR]	= 'X' WHERE [CUSTOMER_FINAL_SHIPTO_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_SHIPTO_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [NET_REVENUE_USD]				= 0 WHERE [NET_REVENUE_USD] IS NULL
UPDATE [ROYALTY].[dbo].[ROYALTY_SAP_ACTUALS_EXT_Q] SET [NET_QTY_PCS]					= 0 WHERE [NET_QTY_PCS] IS NULL

