

-- Parameter
--------------------------------------------
DECLARE @Plan_Active NVARCHAR(MAX)
DECLARE @Plan_Name NVARCHAR(MAX)
DECLARE @Qtr2 NVARCHAR(MAX)
SET @Plan_Active = ?
SET @Plan_Name = ?
SET @Qtr2 = ?



-- 
-- ---------------------------------------------------
TRUNCATE TABLE [ROYALTY].[dbo].[ROYALTY_EPM_Q]

INSERT INTO [ROYALTY].[dbo].[ROYALTY_EPM_Q]
SELECT
	'Y' + [DateYear] AS [YEAR (Yyyyy)],
	SUBSTRING([DateQuarter],1,4) + 'Q' + SUBSTRING([DateQuarter],5,1) AS [QUARTER (yyyyQq)],
	SUBSTRING([DateMonth],1,4) + 'M' + SUBSTRING([DateMonth],5,2) AS [MONTH (yyyyMmm)],

	-- Organization
	'' AS [GROUP_CODE_ORIGINAL],
	'' AS [SUB_GROUP_CODE_ORIGINAL],
	'' AS [DIV_CODE_ORIGINAL],
	SUBSTRING([BUId],1,2) AS [BU_CODE_ORIGINAL],
	SUBSTRING([BUId],1,2) AS [BU_CODE],

	-- Organization
	[VersionVersion] AS [DATA_SOURCE],

	-- Product
	'' AS [PRODUCT_LINE],
	[Commercial_ProductId] AS [CP],

	-- Reason
	'' AS [REASON_CODE],
	[Immaterial_TypeDescription] AS [REASON_DESCR],
	'' AS [REASON_TYPE],
	'' AS [REASON_FLAG_QUANTITY],

	-- Customer Final
	'' AS [CUSTOMER_FINAL_CODE],
	'' AS [CUSTOMER_FINAL_DESCR],
	'' AS [CUSTOMER_FINAL_TYPE_CODE],
	'' AS [CUSTOMER_FINAL_TYPE_DESCR],
	'' AS [CUSTOMER_FINAL_GROUP_CODE],
	'' AS [CUSTOMER_FINAL_GROUP_DESCR],
	IIF([Final_Ship_toId] = '#', [Direct_Customer_Bill_toId] + '01', [Final_Ship_toId])	AS [CUSTOMER_FINAL_SHIPTO_CODE],
	'' AS [CUSTOMER_FINAL_SHIPTO_DESCR],

	-- Revenue, quantity
	SUM([Revenue]) AS [NET_REVENUE_USD],
	SUM([Sales_Quantity_Shared_Business]) AS [NET_QTY_PCS]

FROM [AGRCLFRSSQLPR.AGRMFG.STMMFG.COM\SRMPRD].[EPM].[dbo].[EPM_SMF]
WHERE
	[VersionVersion] = @Plan_Name AND
	'Q' + SUBSTRING([DateQuarter],1,4) + '0' + SUBSTRING([DateQuarter],5,1) = @Qtr2
GROUP BY
	'Y' + [DateYear],
	SUBSTRING([DateQuarter],1,4) + 'Q' + SUBSTRING([DateQuarter],5,1),
	SUBSTRING([DateMonth],1,4) + 'M' + SUBSTRING([DateMonth],5,2),
	SUBSTRING([BUId],1,2),
	[VersionVersion],
	[Commercial_ProductId],
	[Immaterial_TypeDescription],
	IIF([Final_Ship_toId] = '#', [Direct_Customer_Bill_toId] + '01', [Final_Ship_toId])
ORDER BY
	'Y' + [DateYear],
	SUBSTRING([DateQuarter],1,4) + 'Q' + SUBSTRING([DateQuarter],5,1),
	SUBSTRING([DateMonth],1,4) + 'M' + SUBSTRING([DateMonth],5,2),
	SUBSTRING([BUId],1,2),
	[VersionVersion],
	[Commercial_ProductId],
	[Immaterial_TypeDescription],
	IIF([Final_Ship_toId] = '#', [Direct_Customer_Bill_toId] + '01', [Final_Ship_toId])




-- Recupera PL
------------------------------------------------------
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q]
SET 
	[PRODUCT_LINE]	= IIF(t.[PRODUCT_LINE_CODE] IS NOT NULL,t.[PRODUCT_LINE_CODE],	p.[PRODUCT_LINE])
FROM [ROYALTY].[dbo].[ROYALTY_EPM_Q] p
LEFT OUTER JOIN (
		SELECT DISTINCT
			[PRODUCT_CODE_V2],
			[PRODUCT_LINE_CODE]
		FROM [MD].[dbo].[PRODUCT_HIERARCHY_CURR] ) t
ON 
	p.[CP] = t.[PRODUCT_CODE_V2]
 

-- Aggiorna BU, DIV, ecc
------------------------------------------------------
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q]
SET 
	[GROUP_CODE_ORIGINAL]			= IIF(t.[GROUP_CODE] IS NOT NULL,		t.[GROUP_CODE],			p.[GROUP_CODE_ORIGINAL]),
	[SUB_GROUP_CODE_ORIGINAL]		= IIF(t.[SUB_GROUP_CODE] IS NOT NULL,	t.[SUB_GROUP_CODE],		p.[SUB_GROUP_CODE_ORIGINAL]),
	[DIV_CODE_ORIGINAL]			= IIF(t.[DIV_CODE] IS NOT NULL,			t.[DIV_CODE],			p.[DIV_CODE_ORIGINAL])
FROM [ROYALTY].[dbo].[ROYALTY_EPM_Q] p
LEFT OUTER JOIN [MD].[dbo].[PROD_ORG_CURR] t
ON
	p.[BU_CODE] = t.[BU_CODE]


 

-- Aggiorna Customer
------------------------------------------------------
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q]
	SET
		[CUSTOMER_FINAL_CODE]			= IIF(t.[FINAL_SHIP_TO__ID] IS NOT NULL,			t.[FINAL_SHIP_TO__ID],						p.[CUSTOMER_FINAL_CODE]),
		[CUSTOMER_FINAL_DESCR]			= IIF(t.[FINAL_SHORT_NAME] IS NOT NULL,				REPLACE(t.[FINAL_SHORT_NAME],'''',''),		p.[CUSTOMER_FINAL_DESCR]),
		[CUSTOMER_FINAL_TYPE_CODE]		= IIF(t.[FINAL_CUSTOMER_TYPE__CODE] IS NOT NULL,	t.[FINAL_CUSTOMER_TYPE__CODE],				p.[CUSTOMER_FINAL_TYPE_CODE]),
		[CUSTOMER_FINAL_TYPE_DESCR]		= IIF(t.[FINAL_CUSTOMER_TYPE] IS NOT NULL,			REPLACE(t.[FINAL_CUSTOMER_TYPE],'''',''),	p.[CUSTOMER_FINAL_TYPE_DESCR]),
		[CUSTOMER_FINAL_GROUP_CODE]		= IIF(t.[FINAL1_CUSTOMER_GROUP__CODE] IS NOT NULL,	t.[FINAL1_CUSTOMER_GROUP__CODE],			p.[CUSTOMER_FINAL_GROUP_CODE]),
		[CUSTOMER_FINAL_GROUP_DESCR]	= IIF(t.[FINAL1_CUSTOMER_GROUP] IS NOT NULL,		REPLACE(t.[FINAL1_CUSTOMER_GROUP],'''',''), p.[CUSTOMER_FINAL_GROUP_DESCR]),
		[CUSTOMER_FINAL_SHIPTO_DESCR]	= IIF([SHORT_NAME] IS NOT NULL,						REPLACE(t.[SHORT_NAME],'''',''),			p.[CUSTOMER_FINAL_SHIPTO_DESCR])
FROM [ROYALTY].[dbo].[ROYALTY_EPM_Q] p
LEFT OUTER JOIN [MD].[dbo].[CUSTOMER_ASHIPTO_FLAT] t
ON
	p.[CUSTOMER_FINAL_SHIPTO_CODE] = t.[CODE]



-- Limita il numero di decimali di Qty e Rev. Puo' dare degli errori in alcuni casi
--------------------------------------------
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q]
SET 
	[NET_QTY_PCS] = ROUND([NET_QTY_PCS],3,0),
	[NET_REVENUE_USD] = ROUND([NET_REVENUE_USD],4,0)




-- Elimina row dove Rev=0 e Qty=0
--------------------------------------------
DELETE FROM [ROYALTY].[dbo].[ROYALTY_EPM_Q]
WHERE
	[NET_REVENUE_USD] = 0 AND
	[NET_QTY_PCS] = 0






-- Elimina NULL
--------------------------------------------
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [YEAR (Yyyyy)]					= 'X' WHERE [YEAR (Yyyyy)] IS NULL OR LEN([YEAR (Yyyyy)]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [QUARTER (yyyyQq)]				= 'X' WHERE [QUARTER (yyyyQq)] IS NULL OR LEN([QUARTER (yyyyQq)]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [MONTH (yyyyMmm)]				= 'X' WHERE [MONTH (yyyyMmm)] IS NULL OR LEN([MONTH (yyyyMmm)]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [GROUP_CODE_ORIGINAL]			= 'X' WHERE [GROUP_CODE_ORIGINAL] IS NULL OR LEN([GROUP_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [SUB_GROUP_CODE_ORIGINAL]		= 'X' WHERE [SUB_GROUP_CODE_ORIGINAL] IS NULL OR LEN([SUB_GROUP_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [DIV_CODE_ORIGINAL]				= 'X' WHERE [DIV_CODE_ORIGINAL] IS NULL OR LEN([DIV_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [BU_CODE_ORIGINAL]				= 'X' WHERE [BU_CODE_ORIGINAL] IS NULL OR LEN([BU_CODE_ORIGINAL]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [BU_CODE]						= 'X' WHERE [BU_CODE] IS NULL OR LEN([BU_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [DATA_SOURCE]					= 'X' WHERE [DATA_SOURCE] IS NULL OR LEN([DATA_SOURCE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [PRODUCT_LINE]					= 'X' WHERE [PRODUCT_LINE] IS NULL OR LEN([PRODUCT_LINE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CP]								= 'X' WHERE [CP] IS NULL OR LEN([CP]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [REASON_CODE]					= 'X' WHERE [REASON_CODE] IS NULL OR LEN([REASON_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [REASON_DESCR]					= 'X' WHERE [REASON_DESCR] IS NULL OR LEN([REASON_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [REASON_TYPE]					= 'X' WHERE [REASON_TYPE] IS NULL OR LEN([REASON_TYPE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [REASON_FLAG_QUANTITY]			= 'X' WHERE [REASON_FLAG_QUANTITY] IS NULL OR LEN([REASON_FLAG_QUANTITY]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_CODE]			= 'X' WHERE [CUSTOMER_FINAL_CODE] IS NULL OR LEN([CUSTOMER_FINAL_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_DESCR]			= 'X' WHERE [CUSTOMER_FINAL_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_TYPE_CODE]		= 'X' WHERE [CUSTOMER_FINAL_TYPE_CODE] IS NULL OR LEN([CUSTOMER_FINAL_TYPE_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_TYPE_DESCR]		= 'X' WHERE [CUSTOMER_FINAL_TYPE_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_TYPE_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_GROUP_CODE]		= 'X' WHERE [CUSTOMER_FINAL_GROUP_CODE] IS NULL OR LEN([CUSTOMER_FINAL_GROUP_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_GROUP_DESCR]		= 'X' WHERE [CUSTOMER_FINAL_GROUP_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_GROUP_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_SHIPTO_CODE]		= 'X' WHERE [CUSTOMER_FINAL_SHIPTO_CODE] IS NULL OR LEN([CUSTOMER_FINAL_SHIPTO_CODE]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [CUSTOMER_FINAL_SHIPTO_DESCR]	= 'X' WHERE [CUSTOMER_FINAL_SHIPTO_DESCR] IS NULL OR LEN([CUSTOMER_FINAL_SHIPTO_DESCR]) = 0
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [NET_REVENUE_USD]				= 0 WHERE [NET_REVENUE_USD] IS NULL
UPDATE [ROYALTY].[dbo].[ROYALTY_EPM_Q] SET [NET_QTY_PCS]					= 0 WHERE [NET_QTY_PCS] IS NULL


